version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: henrytxz/docker-airflow:c2
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - INSTALL_HIVE=y
            - PYTHONPATH=".:/usr/local/airflow:/usr/local/lib/python3.6/site-packages"
        volumes:
            - ./dag:/usr/local/airflow/dags
            - ./aggr:/usr/local/airflow/aggr
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
